# Prototype workflow for building and passing through druid artifacts

Name: Druid Build workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted

    env:
      DOCKER_IP: 127.0.0.1
      MVN: mvn -B
      # Various options to make execution of maven goals faster (e.g., mvn install)
      MAVEN_SKIP: -P skip-static-checks -Dweb.console.skip=true -Dmaven.javadoc.skip=true
      MAVEN_SKIP_TESTS: -P skip-tests
      MAVEN_OPTS: -Xmx3000m
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'xenial'
      - name: Build with Maven
        run: echo 'Running Maven install...' && ${MVN} clean install -q -ff -pl '!distribution,!:druid-it-image,!:druid-it-cases' ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS} -T1C && ${MVN} install -q -ff -pl 'distribution' ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS}