# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Revised Integration Tests CI
on:
  push:
    branches:
      - master
      - /^\d+\.\d+\.\d+(-\S*)?$/ # release branches
      - 'github-actions-**'
  pull_request:
    branches:
      - master
      - /^\d+\.\d+\.\d+(-\S*)?$/ # release branches

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'maven'
      - name: Maven build
        run: ./it.sh build

  leadership-and-high-availability:
    needs: build
    uses: imply-elliott/druid/.github/workflows/revised_its.yml@github-actions-its
    with:
      compile_jdk: 8
      runtime_jdk: 8
      use_indexer: middleManager
      script: ./it.sh travis HighAvailability

  multi-stage-query:
    needs: build
    uses: imply-elliott/druid/.github/workflows/revised_its.yml@github-actions-its
    with:
      compile_jdk: 8
      runtime_jdk: 8
      use_indexer: middleManager
      script: ./it.sh travis MultiStageQuery

  catalog-integration:
    needs: build
    uses: imply-elliott/druid/.github/workflows/revised_its.yml@github-actions-its
    with:
      compile_jdk: 8
      runtime_jdk: 8
      use_indexer: middleManager
      script: ./it.sh travis Catalog

  batch-index-with-indexer:
    needs: build
    uses: imply-elliott/druid/.github/workflows/revised_its.yml@github-actions-its
    with:
      compile_jdk: 8
      runtime_jdk: 8
      use_indexer: indexer
      script: ./it.sh travis BatchIndex
