# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Combined ITs
on:
  push:
    branches:
      - master
      - /^\d+\.\d+\.\d+(-\S*)?$/ # release branches
      - 'github-actions-**'
  pull_request:
    branches:
      - master
      - /^\d+\.\d+\.\d+(-\S*)?$/ # release branches

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17']
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven
        id: maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.jdk }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.jdk }}-
      - name: Cache targets
        id: target
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ./extendedset/target
            ./hll/target
            ./processing/target
            ./server/target
            ./indexing-hadoop/target
            ./web-console/target
            ./indexing-service/target
            ./services/target
            ./benchmarks/target
            ./distribution/target
            ./integration-tests/target
          key: maven-${{ runner.os }}-${{ matrix.jdk }}-targets-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.jdk }}-targets-
      - name: Cache docker env
        id: docker
        uses: actions/cache@v3
        with:
          path: ./integration-tests-ex/image/target/env.sh
          key: maven-${{ runner.os }}-${{ matrix.jdk }}-docker-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.jdk }}-docker-
      - name: Maven build
        id: maven_build
        run: |
          ./it.sh ci &&
          ./it.sh image
          source ./integration-tests-ex/image/target/env.sh
          docker tag $DRUID_IT_IMAGE_NAME $DRUID_IT_IMAGE_NAME-jdk${{ matrix.jdk }}
          echo "DRUID_IT_IMAGE_NAME=$DRUID_IT_IMAGE_NAME" >> $GITHUB_OUTPUT
]      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "${{ steps.maven_build.outputs.DRUID_IT_IMAGE_NAME }}-jdk${{ matrix.jdk }}"
          retention_days: "2"
    outputs:
      DRUID_IT_IMAGE_NAME: ${{ steps.maven_build.outputs.DRUID_IT_IMAGE_NAME }}

  its:
    needs: build
    uses: imply-elliott/druid/.github/workflows/it.yml@github-actions-its

  ex:
    needs: build
    uses: imply-elliott/druid/.github/workflows/it-ex.yml@github-actions-its
    with:
      druid_it_image_name: "${{ needs.maven_build.outputs.DRUID_IT_IMAGE_NAME }}"
